spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clinic?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:/cn/mapper/*.xml
  type-aliases-package: cn.entity
logging:
  level:
    cn.mapper: debug
